@startuml
!include ./c4/C4_Component.puml
AddRelTag("dotted", $textColor=$ARROW_FONT_COLOR, $lineColor=$ARROW_COLOR, $lineStyle=DottedLine())
AddRelTag("dashed", $textColor=$ARROW_FONT_COLOR, $lineColor=$ARROW_COLOR, $lineStyle=DashedLine())


Container_Boundary(monitoring_back, "Мониторинг"){
    Component(telemetry, "Телеметрия", "Component: Телеметрия", "По расписанию запрашивает данные телеметрии и сохраняет в базу, получения телеметрии в зависимости от типа (файлы, цифровые данные)")
 }
Container_Ext(device_back, "Управление устройствами", "Микросервис", "Работает с устройствами в зависимости от типа")
Container_Ext(profile_back, "Профиль", "Container: Профиль", "Работа с пользователями и привязкой их устройств")
Container_Ext(triggers_back, "Триггеры", "Container: Триггеры", "Работа с триггерами")

ContainerDb_Ext(monitoring_db, "DB Мониторинг", "PostgreSQL", "Справочник устройств, Устройство_мониторинга, Телеметрия")
ContainerQueue_Ext(queue, "Брокер сообщений", "AMPQ")

Rel(telemetry, monitoring_db, "Данные телеметрии, задач мониторинга, справочника устройств", "SQL")
Rel(telemetry, device_back, "Запрос телеметрии")
Rel(profile_back, telemetry, "Добавляет/Удаляет устройство из мониторинга")

Rel(telemetry, queue, "Сообщение о значении телеметрии", "async", $tags="dashed")
Rel(queue, triggers_back, "Сообщение о значении телеметрии", "async", $tags="dashed")


@enduml